<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ReferenceEwalletSeeder extends Seeder
{
    public function run(): void
    {
        $ewallets = [
            [
                'id' => 1737,
                'user_id' => 9,
                'source_id' => 1663,
                'source' => 'bonus',
                'category' => 'commission',
                'nominal' => 15000,
                'percent' => 100,
                'auto_ro' => 0,
                'tax' => 375,
                'amount' => 14625,
                'type' => 'IN',
                'status' => true,
                'description' => 'Bonus Generation Gen-5 dari pendaftaran member kaptensar (2.500 BV)',
                'created_at' => '2025-09-01 14:25:38',
                'updated_at' => '2025-09-01 14:25:38',
            ],
            [
                'id' => 1746,
                'user_id' => 44,
                'source_id' => 1692,
                'source' => 'bonus',
                'category' => 'commission',
                'nominal' => 150000,
                'percent' => 100,
                'auto_ro' => 29250,
                'tax' => 3750,
                'amount' => 117000,
                'type' => 'IN',
                'status' => true,
                'description' => 'Bonus Pairing (2.500 BV)',
                'created_at' => '2025-09-01 14:25:38',
                'updated_at' => '2025-09-01 14:25:38',
            ],
            [
                'id' => 1749,
                'user_id' => 21,
                'source_id' => 1675,
                'source' => 'bonus',
                'category' => 'commission',
                'nominal' => 10000,
                'percent' => 100,
                'auto_ro' => 0,
                'tax' => 250,
                'amount' => 9750,
                'type' => 'IN',
                'status' => true,
                'description' => 'Bonus Unilevel Level-7 dari pendaftaran member brighton (2.500 BV)',
                'created_at' => '2025-09-01 14:41:05',
                'updated_at' => '2025-09-01 14:41:05',
            ],
            [
                'id' => 1769,
                'user_id' => 22,
                'source_id' => 76,
                'source' => 'withdraw',
                'category' => 'commission',
                'nominal' => 1501500,
                'percent' => 100,
                'auto_ro' => 0,
                'tax' => 0,
                'amount' => 1501500,
                'type' => 'OUT',
                'status' => true,
                'description' => 'Withdraw tgl 2025-09-01 Rp 1.501.500',
                'created_at' => '2025-09-01 23:59:00',
                'updated_at' => '2025-09-01 23:59:00',
            ],
        ];

        $withdrawals = [
            [
                'id' => 2,
                'user_id' => 22,
                'bank_account_id' => null,
                'withdraw_type' => 'ewallet',
                'amount' => 497250,
                'amount_received' => 492250,
                'tax_amount' => 0,
                'admin_fee' => 5000,
                'auto_ro_amount' => 0,
                'status' => 'completed',
                'external_reference' => null,
                'inquiry_reference' => null,
                'inquiry_status' => null,
                'payment_reference' => null,
                'payment_status' => null,
                'confirmed_by' => 'masteradmin',
                'confirmed_at' => '2025-04-22 10:47:22',
                'created_at' => '2025-04-21 23:59:00',
                'updated_at' => '2025-04-22 10:47:22',
            ],
            [
                'id' => 5,
                'user_id' => 39,
                'bank_account_id' => null,
                'withdraw_type' => 'ewallet',
                'amount' => 414375,
                'amount_received' => 409375,
                'tax_amount' => 0,
                'admin_fee' => 5000,
                'auto_ro_amount' => 0,
                'status' => 'completed',
                'external_reference' => null,
                'inquiry_reference' => null,
                'inquiry_status' => null,
                'payment_reference' => null,
                'payment_status' => null,
                'confirmed_by' => 'masteradmin',
                'confirmed_at' => '2025-04-23 15:33:26',
                'created_at' => '2025-04-22 23:59:00',
                'updated_at' => '2025-04-23 15:33:26',
            ],
            [
                'id' => 12,
                'user_id' => 42,
                'bank_account_id' => null,
                'withdraw_type' => 'ewallet',
                'amount' => 73125,
                'amount_received' => 68125,
                'tax_amount' => 0,
                'admin_fee' => 5000,
                'auto_ro_amount' => 0,
                'status' => 'completed',
                'external_reference' => null,
                'inquiry_reference' => null,
                'inquiry_status' => null,
                'payment_reference' => null,
                'payment_status' => null,
                'confirmed_by' => 'masteradmin',
                'confirmed_at' => '2025-04-26 10:32:53',
                'created_at' => '2025-04-25 23:59:00',
                'updated_at' => '2025-04-26 10:32:53',
            ],
            [
                'id' => 13,
                'user_id' => 70,
                'bank_account_id' => null,
                'withdraw_type' => 'ewallet',
                'amount' => 599625,
                'amount_received' => 594625,
                'tax_amount' => 0,
                'admin_fee' => 5000,
                'auto_ro_amount' => 0,
                'status' => 'completed',
                'external_reference' => null,
                'inquiry_reference' => null,
                'inquiry_status' => null,
                'payment_reference' => null,
                'payment_status' => null,
                'confirmed_by' => 'masteradmin',
                'confirmed_at' => '2025-04-29 10:33:07',
                'created_at' => '2025-04-28 23:59:00',
                'updated_at' => '2025-04-29 10:33:07',
            ],
        ];

        Schema::disableForeignKeyConstraints();
        DB::table('ewallets')->insertOrIgnore($ewallets);
        DB::table('withdrawals')->insertOrIgnore($withdrawals);
        Schema::enableForeignKeyConstraints();
    }
}
